version: '3.1'

networks:
  dbappnet:
    driver: "bridge"

services:

  mysql_db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    networks:
        - dbappnet
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass

  adminer:
    image: adminer
    restart: always
    networks:
        - dbappnet
    ports:
      - 8080:8080

  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    image: discord-bot
    networks:
        - dbappnet

    
